version: '3.8'

services:
  backend:
    build: ./src/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src/backend:/app

  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
